version: '3.8'

services:
  rustici-engine:
    build:
      context: ./rustici-engine
      dockerfile: Dockerfile
      target: main
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rustici_engine
      - DB_USER=rustici
      - DB_PASSWORD=rustici_password
    depends_on:
      postgres:
        condition: service_healthy
      rustici-installer:
        condition: service_completed_successfully

  rustici-installer:
    build:
      context: ./rustici-engine
      dockerfile: Dockerfile
      target: installer
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rustici_engine
      - DB_USER=rustici
      - DB_PASSWORD=rustici_password
    profiles:
      - install
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=rustici_engine
      - POSTGRES_USER=rustici
      - POSTGRES_PASSWORD=rustici_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rustici -d rustici_engine"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
