version: '3.8'

services:
  rustici-engine:
    build:
      context: ./rustici-engine
      dockerfile: Dockerfile
      target: main
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rusticiengine
      - DB_USER=rusticiengine
      - DB_PASSWORD=super-secret-password
    depends_on:
      postgres:
        condition: service_healthy

  rustici-installer:
    build:
      context: ./rustici-engine
      dockerfile: Dockerfile
      target: installer
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rusticiengine
      - DB_USER=rusticiengine
      - DB_PASSWORD=super-secret-password
    profiles:
      - install
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=super-secret-password
    configs:
      - source: init_dbs.sql
        target: /docker-entrypoint-initdb.d/init_dbs.sql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rusticiengine -d rusticiengine"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

configs:
  init_dbs.sql:
    content: |
      DO $$$$
      BEGIN
         IF NOT EXISTS (
            SELECT FROM pg_catalog.pg_roles
            WHERE  rolname = 'rusticiengine') THEN
            CREATE ROLE rusticiengine LOGIN PASSWORD 'super-secret-password';
         END IF;
      END $$$$;

      CREATE DATABASE rusticiengine WITH OWNER = rusticiengine;

      \c rusticiengine

      GRANT ALL PRIVILEGES ON DATABASE rusticiengine TO rusticiengine;
      GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rusticiengine;
      GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rusticiengine;
      GRANT ALL PRIVILEGES ON SCHEMA public TO rusticiengine;
